name: Main CI workflow

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        php-version: [7.2, 7.3, 7.4]
    
    steps:
    - uses: actions/checkout@v2
    - name: Use PHP ${{ matrix.php-version }}
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-version }}
        tools: composer:v1, 
    - name: Test plugin installation
      run: |
        echo "{\"http-basic\":{\"repo.magento.com\":{\"username\":\"${MAGENTO_USERNAME}\",\"password\":\"${MAGENTO_PASSWORD}\"}}}" > auth.json
        composer install --prefer-dist
      env:
        CI: true
        MAGENTO_USERNAME: ${{ secrets.MAGENTO_USERNAME }}
        MAGENTO_PASSWORD: ${{ secrets.MAGENTO_PASSWORD }}
    - name: Run PHPUnit
      run: vendor/bin/phpunit Test/
    - name: MFTF Tests
      run: |
        sudo apt-get update && sudo apt-get install -y libxslt1-dev libxml2-dev libicu-dev libpng-dev unzip openssh-client libfreetype6-dev libjpeg-dev default-mysql-client chromium-bsu chromium-driver
        sudo mkdir -p /usr/share/man/man1 && sudo apt-get install -y default-jre
        curl -sSL -o selenium-server-standalone.jar https://bit.ly/2TlkRyu
        curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
        composer install
        bin/magento setup:install --base-url=http://127.0.0.1/ --backend-frontname=backendname --db-host=127.0.0.1 --db-name=mftf-tests-db --db-user=root --db-password=password --admin-email=a@b.com --admin-user=admin --admin-password=password123! --admin-firstname=Firstname --admin-lastname=Lastname
        bin/magento config:set web/unsecure/base_url 'http://127.0.0.1/'
        bin/magento config:set web/secure/base_url 'http://127.0.0.1/'
        bin/magento config:set cms/wysiwyg/enabled disabled
        bin/magento config:set admin/security/admin_account_sharing 1
        bin/magento config:set admin/security/use_form_key 0
        bin/magento config:set catalog/search/engine mysql
      env:
        DB_DATABASE: test_db
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
