name: Main CI workflow

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        php-version: [7.3, 7.4]
    
    steps:
    - name: Use PHP ${{ matrix.php-version }}
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-version }}
        tools: composer:v1, 
    - name: Test plugin installation
      run: |
        composer config -a -g http-basic.repo.magento.com ${MAGENTO_USERNAME} ${MAGENTO_PASSWORD}
        composer create-project --repository-url=https://repo.magento.com/ magento/project-community-edition magento
        cd magento
        composer require adyen/module-payment:dev-${GITHUB_REF##*/}
      env:
        CI: true
        MAGENTO_USERNAME: ${{ secrets.MAGENTO_USERNAME }}
        MAGENTO_PASSWORD: ${{ secrets.MAGENTO_PASSWORD }}
    - name: Run PHPUnit
      run: vendor/bin/phpunit vendor/adyen/module-payment/Test/
